# Generated by Django 5.0.7 on 2024-08-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_navigationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
